// NEG-01: malformed input returns ParseErr and never throws — corrupt
// inputs are generated by mutating valid ones. Plus the DRM declaration
// rules and the emptyDocument definition.

import 'dart:convert';
import 'dart:typed_data';

import 'package:ebook_parser/ebook_parser.dart';
import 'package:ebook_parser/src/epub/epub_parser.dart';
import 'package:ebook_parser/src/fb2/fb2_parser.dart';
import 'package:test/test.dart';

import 'support/builders.dart';

void main() {
  final validEpub = (EpubBuilder()
        ..docs.add(EpubDoc('c1.xhtml', '<p>Some text.</p>')))
      .build();
  final validFb2 = fb2Bytes(fb2());

  group('ParseResult surface', () {
    test('valueOrNull is the value on ParseOk and null on ParseErr', () {
      const ok = ParseOk<int>(7);
      const err = ParseErr<int>(
        ParseFailure(ParseFailureKind.corrupt, 'broken zip'),
      );
      expect(ok.valueOrNull, 7);
      expect(err.valueOrNull, isNull);
    });

    test('ParseFailure.toString carries the kind name and the message', () {
      const failure = ParseFailure(ParseFailureKind.corrupt, 'broken zip');
      expect(failure.toString(), 'ParseFailure(corrupt: broken zip)');
    });
  });

  group('corrupt inputs return ParseErr, never throw (NEG-01)', () {
    Future<void> expectCorrupt(
        IBookParser parser, Uint8List bytes, String label) async {
      final parsed = await parser.parse(bytes, fallbackLanguageCode: 'en');
      expect(parsed, isA<ParseErr<BookDocument>>(), reason: label);
      final meta =
          await parser.parseMetadata(bytes, fallbackLanguageCode: 'en');
      expect(meta, isA<ParseErr<BookMetadata>>(), reason: label);
    }

    test('truncated EPUB', () async {
      for (final keep in [10, 100, validEpub.length ~/ 2]) {
        await expectCorrupt(
          EpubParser(),
          Uint8List.sublistView(validEpub, 0, keep),
          'EPUB truncated to $keep bytes',
        );
      }
    });

    test('bit-flipped EPUB central directory', () async {
      final mutated = Uint8List.fromList(validEpub);
      for (var i = mutated.length - 40; i < mutated.length - 20; i++) {
        mutated[i] ^= 0xFF;
      }
      final result =
          await EpubParser().parse(mutated, fallbackLanguageCode: 'en');
      // Either the zip layer refuses it or the reader still finds the
      // container; what is asserted is that nothing throws.
      expect(result, isA<ParseResult<BookDocument>>());
    });

    test('an EPUB with no container.xml is corrupt', () async {
      final zip = buildZip(
        {'random.txt': utf8.encode('hello')},
        mimetypeFirst: true,
      );
      final result =
          await EpubParser().parse(zip, fallbackLanguageCode: 'en');
      expect((result as ParseErr).failure.kind, ParseFailureKind.corrupt);
    });

    test('FB2 with malformed XML is corrupt', () async {
      // Broken inside the description, so the streaming metadata path meets
      // it too; a malformed tail after the description is legitimately
      // never read by that path.
      final broken = fb2Bytes(
        utf8.decode(validFb2).replaceFirst('<description>', '<description><broken'),
      );
      await expectCorrupt(Fb2Parser(), broken, 'unclosed tag');
    });

    test('FB2 with a malformed tail is corrupt on the full parse', () async {
      final broken = fb2Bytes(
        utf8.decode(validFb2).replaceFirst('</FictionBook>', '<unclosed'),
      );
      final result =
          await Fb2Parser().parse(broken, fallbackLanguageCode: 'en');
      expect((result as ParseErr).failure.kind, ParseFailureKind.corrupt);
    });

    test('FB2 truncated mid-document is corrupt', () async {
      await expectCorrupt(
        Fb2Parser(),
        Uint8List.sublistView(validFb2, 0, validFb2.length ~/ 2),
        'truncated FB2',
      );
    });

    test('random bytes fed directly to each parser', () async {
      final junk =
          Uint8List.fromList(List.generate(512, (i) => (i * 31) % 256));
      await expectCorrupt(EpubParser(), junk, 'junk to EpubParser');
      await expectCorrupt(Fb2Parser(), junk, 'junk to Fb2Parser');
    });

    test('non-FB2 XML is unsupportedFormat', () async {
      final xml = fb2Bytes('<?xml version="1.0"?><html><body/></html>');
      final result =
          await Fb2Parser().parse(xml, fallbackLanguageCode: 'en');
      expect(
        (result as ParseErr).failure.kind,
        ParseFailureKind.unsupportedFormat,
      );
    });
  });

  group('hostile XML stays bounded', () {
    test('deeply nested FB2 sections either parse or fail, without hanging',
        () async {
      const depth = 3000;
      final nested = StringBuffer('<body>');
      for (var i = 0; i < depth; i++) {
        nested.write('<section>');
      }
      nested.write('<p>Deep.</p>');
      for (var i = 0; i < depth; i++) {
        nested.write('</section>');
      }
      nested.write('</body>');
      final bytes = fb2Bytes(fb2(bodiesXml: nested.toString()));
      final result = await Fb2Parser()
          .parse(bytes, fallbackLanguageCode: 'en')
          .timeout(const Duration(seconds: 30));
      expect(result, isA<ParseResult<BookDocument>>());
    });

    test('an entity-expansion bomb does not explode', () async {
      // package:xml does not expand custom DTD entities; pin that the
      // outcome is a bounded parse or a ParseErr, never a hang or a crash.
      final bomb = '''
<?xml version="1.0"?>
<!DOCTYPE FictionBook [
  <!ENTITY a "aaaaaaaaaa">
  <!ENTITY b "&a;&a;&a;&a;&a;&a;&a;&a;&a;&a;">
  <!ENTITY c "&b;&b;&b;&b;&b;&b;&b;&b;&b;&b;">
  <!ENTITY d "&c;&c;&c;&c;&c;&c;&c;&c;&c;&c;">
]>
<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0">
  <description><title-info><book-title>&d;&d;&d;</book-title></title-info></description>
  <body><section><p>&d;</p></section></body>
</FictionBook>
''';
      final result = await Fb2Parser()
          .parse(fb2Bytes(bomb), fallbackLanguageCode: 'en')
          .timeout(const Duration(seconds: 30));
      expect(result, isA<ParseResult<BookDocument>>());
      if (result is ParseOk<BookDocument>) {
        // If it parsed, the entities were not exponentially expanded.
        final text = result.value.bodySample();
        expect(text.length, lessThan(1000000));
      }
    });
  });

  group('DRM declarations (DEC-32)', () {
    Uint8List epubWithEncryption(String encryptionXml) {
      final builder = EpubBuilder()
        ..docs.add(EpubDoc('c1.xhtml', '<p>Some text.</p>'))
        ..files['META-INF/encryption.xml'] = utf8.encode(encryptionXml);
      return builder.build();
    }

    const contentEncryption = '''
<?xml version="1.0"?>
<encryption xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <EncryptedData xmlns="http://www.w3.org/2001/04/xmlenc#">
    <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
    <CipherData><CipherReference URI="c1.xhtml"/></CipherData>
  </EncryptedData>
</encryption>
''';

    const fontObfuscation = '''
<?xml version="1.0"?>
<encryption xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <EncryptedData xmlns="http://www.w3.org/2001/04/xmlenc#">
    <EncryptionMethod Algorithm="http://www.idpf.org/2008/embedding"/>
    <CipherData><CipherReference URI="fonts/serif.ttf"/></CipherData>
  </EncryptedData>
</encryption>
''';

    const imageEncryption = '''
<?xml version="1.0"?>
<encryption xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <EncryptedData xmlns="http://www.w3.org/2001/04/xmlenc#">
    <EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
    <CipherData><CipherReference URI="images/pic.jpeg"/></CipherData>
  </EncryptedData>
</encryption>
''';

    test('encryption over a content document is drmProtected on both paths',
        () async {
      final bytes = epubWithEncryption(contentEncryption);
      final parser = EpubParser();
      final parsed = await parser.parse(bytes, fallbackLanguageCode: 'en');
      expect(
        (parsed as ParseErr).failure.kind,
        ParseFailureKind.drmProtected,
      );
      final meta =
          await parser.parseMetadata(bytes, fallbackLanguageCode: 'en');
      expect(
        (meta as ParseErr).failure.kind,
        ParseFailureKind.drmProtected,
      );
    });

    test('font obfuscation alone parses normally on both paths', () async {
      final bytes = epubWithEncryption(fontObfuscation);
      final parser = EpubParser();
      final parsed = await parser.parse(bytes, fallbackLanguageCode: 'en');
      expect(parsed, isA<ParseOk<BookDocument>>());
      final meta =
          await parser.parseMetadata(bytes, fallbackLanguageCode: 'en');
      expect(meta, isA<ParseOk<BookMetadata>>());
    });

    test('encryption covering only images still counts as content', () async {
      final bytes = epubWithEncryption(imageEncryption);
      final result =
          await EpubParser().parse(bytes, fallbackLanguageCode: 'en');
      expect(
        (result as ParseErr).failure.kind,
        ParseFailureKind.drmProtected,
      );
    });

    test('META-INF/rights.xml is drmProtected', () async {
      final builder = EpubBuilder()
        ..docs.add(EpubDoc('c1.xhtml', '<p>Some text.</p>'))
        ..files['META-INF/rights.xml'] = utf8.encode('<rights/>');
      final result = await EpubParser()
          .parse(builder.build(), fallbackLanguageCode: 'en');
      expect(
        (result as ParseErr).failure.kind,
        ParseFailureKind.drmProtected,
      );
    });
  });

  group('emptyDocument means no blocks, not no text (SC-09, DEC-21)', () {
    test('an EPUB with no blocks anywhere is emptyDocument', () async {
      final builder = EpubBuilder()
        ..docs.add(EpubDoc('c1.xhtml', ''))
        ..docs.add(EpubDoc('c2.xhtml', '<div></div>'));
      final result = await EpubParser()
          .parse(builder.build(), fallbackLanguageCode: 'en');
      expect(
        (result as ParseErr).failure.kind,
        ParseFailureKind.emptyDocument,
      );
    });

    test('an FB2 with no blocks anywhere is emptyDocument', () async {
      final bytes = fb2Bytes(fb2(
        bodiesXml: '<body><section></section></body>',
      ));
      final result =
          await Fb2Parser().parse(bytes, fallbackLanguageCode: 'en');
      expect(
        (result as ParseErr).failure.kind,
        ParseFailureKind.emptyDocument,
      );
    });

    test('an image-only book parses and its bodySample is empty', () async {
      final builder = EpubBuilder()
        ..docs.add(EpubDoc(
            'c1.xhtml', '<div><img src="pic.png" alt=""/></div>'))
        ..files['pic.png'] = kTinyPng;
      final result = await EpubParser()
          .parse(builder.build(), fallbackLanguageCode: 'en');
      expect(result, isA<ParseOk<BookDocument>>());
      final doc = (result as ParseOk<BookDocument>).value;
      expect(doc.chapters.single.blocks.single, isA<ImageBlock>());
      expect(doc.bodySample(), '');
    });

    test('an image-only FB2 parses too', () async {
      final bytes = fb2Bytes(fb2(
        bodiesXml:
            '<body><section><image l:href="#pic"/></section></body>',
        binariesXml: fb2Binary('pic', kTinyPng),
      ));
      final result =
          await Fb2Parser().parse(bytes, fallbackLanguageCode: 'en');
      expect(result, isA<ParseOk<BookDocument>>());
      expect(
        (result as ParseOk<BookDocument>).value.bodySample(),
        '',
      );
    });
  });

  test('a bad fallbackLanguageCode throws ArgumentError, not ParseErr',
      () async {
    expect(
      () => EpubParser().parse(validEpub, fallbackLanguageCode: 'nope'),
      throwsArgumentError,
    );
    expect(
      () => Fb2Parser()
          .parseMetadata(validFb2, fallbackLanguageCode: 'klingon'),
      throwsArgumentError,
    );
  });
}
